---
title: "capbility_trust"
format: html
editor: visual
---

# setup

```{r setup,include = FALSE,echo=FALSE}
set.seed(0312)
options (warn = -1)
setwd("/Users/zhumeng/Desktop/Spring semester_2023/research/code")
# packbirth loading
library(pacman)
p_load("rio",
       "here",
       "tidyverse",
       "scales",
       "car",
       "haven",
       "psych",
       "lavaan",
       "mirt",
       "modelsummary")
```

# dataloda
# cbs
## cbs2002

```{r cbs2002, echo=FALSE}
# no socilalevel
cbs2002_raw <- read_dta("../data/cbs/cbs2002.dta") %>%
  mutate(year = 2002,
         wave = 1)
cbs2002_raw[cbs2002_raw < 0] <- NA
cbs2002 <- cbs2002_raw %>%
  dplyr::select(.,q1,q2,province_id,v82,v83,v2,v84,v17,v18,v19,v20,v21,v22,v111,v110,v109,v101,v123,v130,v73a,v73b,v73c,year,wave)  %>%
  rename(id = q1)

# area
cbs2002$time <- if_else(cbs2002$year < 2015, 0, 1)
cbs2002$province <- as.character(cbs2002$province_id) %>%
  dplyr::recode(
         "11" = "北京市", 
         "12" = "天津市", 
         "13" = "河北省", 
         "14" = "山西省", 
         "15" = "内蒙古自治区", 
         "21" = "辽宁省", 
         "22" = "吉林省", 
         "23" = "黑龙江省", 
         "31" = "上海市", 
         "32" = "江苏省", 
         "33" = "浙江省", 
         "34" = "安徽省", 
         "35" = "福建省", 
         "36" = "江西省", 
         "37" = "山东省", 
         "41" = "河南省", 
         "42" = "湖北省", 
         "43" = "湖南省", 
         "44" = "广东省", 
         "45" = "广西壮族自治区", 
         "46" = "海南省", 
         "50" = "重庆市", 
         "51" = "四川省", 
         "52" = "贵州省", 
         "53" = "云南省", 
         "54" = "西藏自治区", 
         "61" = "陕西省", 
         "62" = "甘肃省", 
         "63" = "青海省", 
         "64" = "宁夏回族自治区", 
         "65" = "新疆维吾尔自治区")

#filter(.,!(v100 == 997)) #997没有回答
cbs2002$female <- cbs2002$v82 - 1
cbs2002$age <- cbs2002$v83
cbs2002$marriage <- Recode(cbs2002$v123,"9 = NA")
cbs2002$hukouRural <- Recode(cbs2002$v2, "2 = 0; c(3,7) = NA") # 
cbs2002$race <- Recode(cbs2002$v84, "2:33 = 0; c(0,98) = 0") 
cbs2002$party <- Recode(cbs2002$v111,"c(1,2,4,9) = 0; 3 =1") 
cbs2002$edu <- Recode(cbs2002$v110, "0:1 = 1; 2 = 2; 3:4 = 3; 5 = 4; 6 = 5; 9 = NA")

# iv
cbs2002$staten <- cbs2002$v17
cbs2002$statep <- cbs2002$v18
cbs2002$statef <- cbs2002$v19

cbs2002$famn <- cbs2002$v20
cbs2002$famp <- cbs2002$v21
cbs2002$famf <- cbs2002$v22

# dv
cbs2002$trust_gover <- cbs2002$v73b
cbs2002$trust_gover_z <- Recode(cbs2002$v73b,"c(0,8,9) = NA") 
cbs2002$trust_gover_z <- scales::rescale(as.numeric(cbs2002$trust_gover_z),to = c(0,1)) 
cbs2002$trust_goverR <- Recode(cbs2002$v73b,"4:6 = 1; 1:3 = 0; c(0,8,9) = NA") 
cbs2002$trust_gover_max <- Recode(cbs2002$v73b,"1:5 = 0; 6 = 1;c(0,8,9) = NA")

cbs2002$trust_local <- cbs2002$v73c
cbs2002$trust_local_z <- Recode(cbs2002$v73c,"c(0,8,9) = NA") 
cbs2002$trust_local_z <- scales::rescale(as.numeric(cbs2002$trust_local_z),to = c(0,1)) 
cbs2002$trust_localR <- Recode(cbs2002$v73c,"4:6 = 1; 1:3 = 0; c(0,8,9) = NA")  


write.csv(cbs2002,file = "../dataclean/cbs2002.csv")
```

## cbs2008

```{r cbs2008}
cbs2008_raw <- haven::read_dta("../data/cbs/cbs2008.dta") %>%
  mutate(year = 2008,
         wave = 1) 
#data2008 <- cbs2008_raw %>%
#  select(.,number,j8,j8s8k,J16)

#write.csv(data2008,file = "../data/cbs/data2008.csv")

data2008 <- read.csv("../data/cbs/data2008.csv") %>%
  select(.,number,occR) %>%
  rename(id = number)

cbs2008 <- cbs2008_raw %>%
  dplyr::select(.,number,a1,j1,j2,j3,j3a,j4,j8,j28,j35,PROV,c5,c6,c7,c8,c9,c10,c11,f30a,f30b,f30c,year,wave)  %>%
  rename(id = number) %>%
  left_join(.,data2008)

# area
cbs2008$time <- if_else(cbs2008$year < 2015, 0, 1)
cbs2008$province <- as.character(cbs2008$PROV) %>%
  dplyr::recode(
         "11" = "北京市", 
         "12" = "天津市", 
         "13" = "河北省", 
         "14" = "山西省", 
         "15" = "内蒙古自治区", 
         "21" = "辽宁省", 
         "22" = "吉林省", 
         "23" = "黑龙江省", 
         "31" = "上海市", 
         "32" = "江苏省", 
         "33" = "浙江省", 
         "34" = "安徽省", 
         "35" = "福建省", 
         "36" = "江西省", 
         "37" = "山东省", 
         "41" = "河南省", 
         "42" = "湖北省", 
         "43" = "湖南省", 
         "44" = "广东省", 
         "45" = "广西壮族自治区", 
         "46" = "海南省", 
         "50" = "重庆市", 
         "51" = "四川省", 
         "52" = "贵州省", 
         "53" = "云南省", 
         "54" = "西藏自治区", 
         "61" = "陕西省", 
         "62" = "甘肃省", 
         "63" = "青海省", 
         "64" = "宁夏回族自治区", 
         "65" = "新疆维吾尔自治区")

cbs2008$female <- cbs2008$j1 - 1
cbs2008$age <- cbs2008$j2
cbs2008$marriage <- Recode(cbs2008$j35,"c(1,2,3,4,5,6) = 0; 2 = 1; 9 = NA")
cbs2008$hukouRural <- Recode(cbs2008$a1, "2 = 0; c(3,9) = NA") 
cbs2008$race <- Recode(cbs2008$j4, "2 = 0; c(98,99) = 0") 
cbs2008$party <- Recode(cbs2008$j28,"1:2 = 0; 3:4 =1; 9 = NA") 
cbs2008$edu <- Recode(cbs2008$j3, "0:1 = 1; 2:3 = 2; 4:6 = 3; 7 = 4; 8 = 5; 9 = NA")
cbs2008$eduyear <- cbs2008$j3a



# iv
cbs2008$statepolicy <- cbs2008$c5
cbs2008$staten <- cbs2008$c6
cbs2008$statep <- cbs2008$c7
cbs2008$statef <- cbs2008$c8

cbs2008$famn <- cbs2008$c9
cbs2008$famp <- cbs2008$c10
cbs2008$famf <- cbs2008$c11

# dv
cbs2008$trust_gover <- cbs2008$f30b
cbs2008$trust_gover_z <- Recode(cbs2008$f30b,"7:9 = NA")
cbs2008$trust_gover_z <- scales::rescale(as.numeric(cbs2008$trust_gover_z),to = c(0,1)) 
cbs2008$trust_goverR <- Recode(cbs2008$f30b,"4:6 = 1; 1:3 = 0; 7:9 = NA") 
cbs2008$trust_gover_max <- Recode(cbs2008$f30b,"6 = 1; 1:5 = 0; 7:9 = NA")

cbs2008$trust_local <- cbs2008$f30c
cbs2008$trust_local_z <- Recode(cbs2008$f30c,"7:9 = NA") 
cbs2008$trust_local_z <- scales::rescale(as.numeric(cbs2008$trust_local_z),to = c(0,1)) 
cbs2008$trust_localR <- Recode(cbs2008$f30c,"4:6 = 1; 1:3 = 0; 7:9 = NA")  

cbs2008$trust_court <- cbs2008$f30a
cbs2008$trust_court_z <- Recode(cbs2008$f30a,"7:9 = NA") 
cbs2008$trust_court_z <- scales::rescale(as.numeric(cbs2008$trust_court_z),to = c(0,1)) 
cbs2008$trust_courtR <- Recode(cbs2008$f30a,"4:6 = 1; 1:3 = 0; 7:9 = NA")

write.csv(cbs2008,file = "../dataclean/cbs2008.csv")
#cbs2008 <-  as.data.frame (as.data.set(spss.system.file("../data/cbs/cbs2008.sav"))) %>%
#  mutate(year = 2008,
#         wave = 1)

```

## cbs2011

```{r cbs2011}
cbs2011_raw <- haven::read_dta("../data/cbs/cbs2011.dta") %>%
  mutate(year = 2011,
         wave = 1) %>%
  dplyr::rename("id" = "idnumber")

data <- read.csv("../data/cbs/data2011.csv")
cbs2011 <- cbind(cbs2011_raw,data)
write.csv(cbs2011_raw,file = "../data/cbs/cbs2011.csv")

cbs2011$province <- as.character(cbs2011$PROVINCE) %>%
  dplyr::recode(
         "1" = "上海市",
         "2" = "辽宁省",
         "3" = "河南省",
         "4" = "广东省",
         "5" = "甘肃省", 
         "6" = "北京市",
         "7" = "天津市", 
         "8" = "河北省", 
         "9" = "山西省",
         "10" = "吉林省",
         "11" = "黑龙江省",
         "12" = "江苏省",
         "13" = "浙江省", 
         "14" = "安徽省",
         "15" = "福建省",
         "16" = "江西省",
         "17" = "山东省",
         "18" = "湖北省", 
         "19" = "湖南省", 
         "20" = "广西壮族自治区",
         "21" = "重庆市", 
         "22" = "四川省", 
         "23" = "贵州省", 
         "24" = "云南省", 
         "25" = "陕西省") 

cbs2011$time <- if_else(cbs2011$year < 2015, 0, 1)
cbs2011$female <- cbs2011$SEX - 1
cbs2011$age <- cbs2011$SE2
cbs2011$corhort <- Recode(cbs2011$SE2,"18:29 = 1; 30:49 = 2; 50:69 = 3; 70:94 = 4")
cbs2011$hukouRural <- Recode(cbs2011$A1,"2 = 0; c(3,9) = NA")
cbs2011$marriage <- Recode(cbs2011$SE29,"2 = 1; c(1,3,4,5,6) = 0; 9 = NA")
cbs2011$party <- Recode(cbs2011$SE22,"c(1,2,9) = 0;3:4 = 1")
cbs2011$socialLevel <- Recode(cbs2011$SE21,"98:99 = NA")
cbs2011$race <- Recode(cbs2011$SE4,"c(98,99,2) = 0")
cbs2011$edu <- Recode(cbs2011$SE3,"0:1 = 1; 2:3 = 2;4:6 = 3; 7 = 4; 8 = 5; 9 = NA")

# iv
cbs2011$staten <- cbs2011$A12
cbs2011$statep <- cbs2011$A13
cbs2011$statef <- cbs2011$A14

cbs2011$famn <- cbs2011$A15
cbs2011$famp <- cbs2011$A16
cbs2011$famf <- cbs2011$A17


cbs2011$trust_gover <- cbs2011$C17b
cbs2011$trust_gover_z <- Recode(cbs2011$C17b,"7:9 = NA")
cbs2011$trust_gover_z <- scales::rescale(as.numeric(cbs2011$trust_gover_z),to = c(0,1))
cbs2011$trust_goverR <- Recode(cbs2011$C17b,"1:3 = 0;4:6 = 1; 7:9 = NA")
cbs2011$trust_gover_max <- Recode(cbs2011$C17b,"6 = 1; 1:5 = 0; 7:9 = NA")

cbs2011$trust_court <- cbs2011$C17a
cbs2011$trust_court_z <- Recode(cbs2011$C17a,"7:9 = NA")
cbs2011$trust_court_z <- scales::rescale(as.numeric(cbs2011$trust_court_z),to = c(0,1))
cbs2011$trust_courtR <- Recode(cbs2011$C17a,"1:3 = 0; 4:6 = 1; 7:9 = NA")
cbs2011$trust_local <- cbs2011$C17h
cbs2011$trust_local_z <- Recode(cbs2011$C17h,"7:9 = NA")
cbs2011$trust_local_z <- scales::rescale(as.numeric(cbs2011$trust_local_z),to = c(0,1))
cbs2011$trust_localR <- Recode(cbs2011$C17h,"1:3 = 0; 4:6 = 1;7:9 = NA")
```

## cbs2014

```{r cbs2014}
cbs2014_raw <- haven::read_sav("../data/cbs/cbs2014.sav") %>%
  mutate(year = 2014,
         wave = 1)

cbs2014_raw[cbs2014_raw < 0] <- NA
cbs2014 <- cbs2014_raw %>%
  dplyr::select(.,CASEID,Proid,A1,A2,A3A,A4,B15,B16,B17,B18,B19,B20,SE1,SE1A,SE9,SE17,SE8,SE4,SE3,SE2,E1A,E1B,E1H,year,wave) %>%
  dplyr::rename(id = CASEID)
cbs2014$province <- as.character(cbs2014$Proid) %>%
  dplyr::recode(
         "11" = "北京市", 
         "12" = "天津市", 
         "13" = "河北省", 
         "14" = "山西省", 
         "15" = "内蒙古自治区", 
         "21" = "辽宁省", 
         "22" = "吉林省", 
         "23" = "黑龙江省", 
         "31" = "上海市", 
         "32" = "江苏省", 
         "33" = "浙江省", 
         "34" = "安徽省", 
         "35" = "福建省", 
         "36" = "江西省", 
         "37" = "山东省", 
         "41" = "河南省", 
         "42" = "湖北省", 
         "43" = "湖南省", 
         "44" = "广东省", 
         "45" = "广西壮族自治区", 
         "46" = "海南省", 
         "50" = "重庆市", 
         "51" = "四川省", 
         "52" = "贵州省", 
         "53" = "云南省", 
         "54" = "西藏自治区", 
         "61" = "陕西省", 
         "62" = "甘肃省", 
         "63" = "青海省", 
         "64" = "宁夏回族自治区", 
         "65" = "新疆维吾尔自治区")

cbs2014$time <- if_else(cbs2014$year < 2015, 0, 1)
cbs2014$female <- Recode(cbs2014$A1,"1 = 0; 2 = 1; 9 = NA") 
cbs2014$age <- cbs2014$A3A
cbs2014$corhort <- Recode(cbs2014$age,"18:29 = 1; 30:49 = 2; 50:69 = 3; 70:99 = 4")
# 99岁的有133个人
cbs2014$marriage <- Recode(cbs2014$SE17,"c(1,3,4,5,6) = 0; 2 = 1; 9 = NA")
cbs2014$socialLevel <- Recode(cbs2014$SE8,"98:99 = NA")
cbs2014$hukouRural <- Recode(cbs2014$A2,"2 = 0; c(3,9) = NA")
cbs2014$race <- Recode(cbs2014$A4,"c(8,9,2) = 0")
cbs2014$edu <- Recode(cbs2014$SE1, "0:1 = 1; 2:3 = 2; 4:6 = 3; 7 = 4;8 = 5; 9 = NA")
cbs2014$eduyear <- cbs2014$SE1A
cbs2014$party <- Recode(cbs2014$SE9,"3:4 = 1; c(1,2,9) = 0")

# iv
cbs2014$staten <- cbs2014$B15
cbs2014$statep <- cbs2014$B16
cbs2014$statef <- cbs2014$B17

cbs2014$famn <- cbs2014$B18
cbs2014$famp <- cbs2014$B19
cbs2014$famf <- cbs2014$B20

# dv

cbs2014$trust_gover <- cbs2014$E1B
cbs2014$trust_gover_z <- Recode(cbs2014$E1B,"7:9 = NA") 
cbs2014$trust_gover_z <- scales::rescale(as.numeric(cbs2014$trust_gover_z),to = c(0,1)) 
cbs2014$trust_goverR <- Recode(cbs2014$E1B,"4:6 = 1; 1:3 = 0; 7:9 = NA") 
cbs2014$trust_gover_max <- Recode(cbs2014$E1B,"6 = 1; 1:5 = 0; 7:9 = NA")

cbs2014$trust_local <- cbs2014$E1H
cbs2014$trust_local_z <- Recode(cbs2014$E1H,"7:9 = NA") 
cbs2014$trust_local_z <- scales::rescale(as.numeric(cbs2014$trust_local_z),to = c(0,1)) 
cbs2014$trust_localR <- Recode(cbs2014$E1H,"4:6 = 1; 1:3 = 0; 7:9 = NA")

cbs2014$trust_court <- cbs2014$E1A
cbs2014$trust_court_z <- Recode(cbs2014$E1A,"7:9 = NA") 
cbs2014$trust_court_z <- scales::rescale(as.numeric(cbs2014$trust_court_z),to = c(0,1)) 
cbs2014$trust_courtR <- Recode(cbs2014$E1A,"4:6 = 1; 1:3 = 0; 7:9 = NA")

write.csv(cbs2014,file = "../dataclean/cbs2014.csv")
```

## cbs2019

```{r cbs2019}
cbs2019_raw <- haven::read_sav("../data/cbs/cbs2019.sav") %>%
  mutate(year = 2019,
         wave = 1)

cbs2019 <- cbs2019_raw %>%
  dplyr::select(.,"个案编号",SITEPRO,A1,A2,A4A,A5,B15,B16,B17,B18,B19,B20,SE1,SE1A,SE11,SE13,SE22,SE5,E4A,E4B,E4H,year,wave) %>%
  dplyr::rename(province = SITEPRO,
         id = "个案编号")

cbs2019$province[cbs2019$province == "上海"] <- "上海市"
cbs2019$province[cbs2019$province == "北京"] <- "北京市"
cbs2019$province[cbs2019$province == "北京"] <- "北京市"
cbs2019$province[cbs2019$province == "重庆"] <- "重庆市"
cbs2019$province[cbs2019$province == "云南"] <- "云南省"
cbs2019$province[cbs2019$province == "吉林"] <- "吉林省"
cbs2019$province[cbs2019$province == "四川"] <- "四川省"
cbs2019$province[cbs2019$province == "安徽"] <- "安徽省"
cbs2019$province[cbs2019$province == "山东"] <- "山东省"
cbs2019$province[cbs2019$province == "江苏"] <- "江苏省"
cbs2019$province[cbs2019$province == "广西"] <- "广西壮族自治区"
cbs2019$province[cbs2019$province == "广东"] <- "广东省"
cbs2019$province[cbs2019$province == "江西"] <- "江西省"
cbs2019$province[cbs2019$province == "河南"] <- "河南省"
cbs2019$province[cbs2019$province == "浙江"] <- "浙江省"
cbs2019$province[cbs2019$province == "湖南"] <- "湖南省"
cbs2019$province[cbs2019$province == "甘肃"] <- "甘肃省"
cbs2019$province[cbs2019$province == "贵州"] <- "贵州省"
cbs2019$province[cbs2019$province == "福建"] <- "福建省"
cbs2019$province[cbs2019$province == "黑龙江"] <- "黑龙江省"

cbs2019$time <- if_else(cbs2019$year < 2015, 0, 1)
cbs2019$female <- cbs2019$A1 - 1
cbs2019$age <- cbs2019$A4A
cbs2019$corhort <- Recode(cbs2019$age,"18:29 = 1; 30:49 = 2; 50:69 = 3; 70:94 = 4")
cbs2019$marriage <- Recode(cbs2019$SE22,"c(1,3,4,5,6) = 0; 2 = 1")
cbs2019$socialLevel <- cbs2019$SE11
cbs2019$hukouRural <- Recode(cbs2019$A2,"c(2,3) = 0; c(1,4) = 1; c(5,9) = NA")
cbs2019$race <- Recode(cbs2019$A5,"2 = 0")
cbs2019$edu <- Recode(cbs2019$SE1, "0:3 = 1; 4:5 = 2; 6:8 = 3; 9 = 3; 10 = 5")
cbs2019$eduyear <- cbs2019$SE1A
cbs2019$party <- Recode(cbs2019$SE13,"3:4 = 1; 1:2 = 0")


# iv
cbs2019$staten <- cbs2019$B15
cbs2019$statep <- cbs2019$B16
cbs2019$statef <- cbs2019$B17

cbs2019$famn <- cbs2019$B18
cbs2019$famp <- cbs2019$B19
cbs2019$famf <- cbs2019$B20

# dv
cbs2019$trust_gover <- cbs2019$E4B
cbs2019$trust_gover_z <- scales::rescale(as.numeric(cbs2019$E4B),to = c(0,1)) 
cbs2019$trust_goverR <- Recode(cbs2019$E4B,"4:6 = 1; 1:3 = 0")
cbs2019$trust_gover_max <- Recode(cbs2019$E4B,"6 = 1; 1:5 = 0")

cbs2019$trust_local <- cbs2019$E4H
cbs2019$trust_local_z <- scales::rescale(as.numeric(cbs2019$E4H),to = c(0,1))
cbs2019$trust_localR <- Recode(cbs2019$E4H,"4:6 = 1; 1:3 = 0")

cbs2019$trust_court <- cbs2019$E4A
cbs2019$trust_court_z <- scales::rescale(as.numeric(cbs2019$E4A),to = c(0,1)) 
cbs2019$trust_courtR <- Recode(cbs2019$E4A,"4:6 = 1; 1:3 = 0")
write.csv(cbs2019,file = "../dataclean/cbs2019.csv")

```






# factorAnalysis

```{r factor,results='asis',echo=F,warning=F,message=F}
# factor analysis

fac_css2017 <-
 'economy = ~ jiuye + shouru + shebao 
  governce = ~ zhifa + fubai + zhian 
  public = ~ jiaoyu + huanjing + yiliao'

fit_css2017 <- cfa(fac_css2017, data = css2017,std.lv = TRUE)

summary(fit_css2017, fit.measures = TRUE, standardized = TRUE)

# KMO test and  Bartlett test
eco_css2017 <- css2017 %>%
  dplyr::select(jiuye, shebao, shouru) %>%
  drop_na()

eco_kmo <- KMO(eco_css2017)
eco_bartlett <- cortest.bartlett(eco_css2017,diag=TRUE)

gover_css2017 <- css2017 %>%
  dplyr::select(zhian, zhifa, fubai) %>%
  drop_na()
gover_kmo <- KMO(gover_css2017)
gover_bartlett <- cortest.bartlett(gover_css2017,diag=TRUE)

public_css2017 <- css2017 %>%
  dplyr::select(jiaoyu,huanjing,yiliao)
public_kmo <- KMO(public_css2017)
public_bartlett <- cortest.bartlett(public_css2017,diag=TRUE)

#①MO。用于检查变量间的偏相关性，取值在0-1之间。KMO值越接近于1，变量间的偏相关性就越强，因子分析效果就好。KMO值0.9以上极适合做因子分析，0.8以上适合做因子分析，0.7以上尚可，0.6以上勉强度可以，0.5以上不适合，0.5以下非常不适合。实际运用中，在0.7以上，效果比较好；在0.5以下时，不适合应用因子分析。
#Bartlett球形检验。用于判断相关矩阵是否是单位阵，即各变量是否有较强的版相关性。P<.05,不服从球形检验，应拒绝各权变量独立的假设，即变量间有较强相关；P>.05时，服从球形检验，各变量相互独立，不能做因子分析。

```

# dataCombine

```{r warning = FALSE}
df_cbs2002 <- cbs2002 %>%
  dplyr::select(id,province,year,age,female,party,race,hukouRural,marriage,edu,staten,statep,statef,famn,famp,famf,trust_gover,trust_goverR,trust_gover_z,trust_gover_max,trust_local) 

df_cbs2008 <- cbs2008 %>%
  dplyr::select(id,province,year,age,female,party,race,hukouRural,marriage,edu,staten,statep,statef,famn,famp,famf,trust_gover,trust_goverR,trust_gover_z,trust_gover_max,trust_local) 

df_cbs2011 <- cbs2011 %>%
  dplyr::select(id,province,year,age,female,party,race,hukouRural,marriage,edu,staten,statep,statef,famn,famp,famf,trust_gover,trust_goverR,trust_gover_z,trust_gover_max,trust_local) 

df_cbs2014 <- cbs2014 %>%
  dplyr::select(id,province,year,age,female,party,race,hukouRural,marriage,edu,staten,statep,statef,famn,famp,famf,trust_gover,trust_goverR,trust_gover_z,trust_gover_max,trust_local) 

df_cbs2019 <- cbs2019 %>%
  dplyr::select(id,province,year,age,female,party,race,hukouRural,marriage,edu,staten,statep,statef,famn,famp,famf,trust_gover,trust_goverR,trust_gover_z,trust_gover_max,trust_local) 


fullData <- bind_rows(
  df_cbs2002,
  df_cbs2008,
  df_cbs2011,
  df_cbs2014,
  df_cbs2019
)

fullDatam <- fullData %>%
  group_by(year) %>%
  summarise(trust_gover_m = mean(trust_gover,na.rm = T),
            trust_gover_rm = mean(trust_goverR,na.rm = T),
            trust_gover_zm = mean(trust_gover_z,na.rm = T),
            trust_local_m = mean(trust_local,na.rm = T)) %>%
  drop_na()



```

# dataDescription

## tableDescription

```{r dataDescription, results='asis',warning=FALSE}
## fulldata descriptive
datasummary(
    data = fullData,
    output = "../table/Descriptive.docx",
      (Economy = eco) +
      (Governmence = gover) +
      (Public = public) +
      (`Central goverment` = trust_gover)  +
      (`Central govermentR` = trust_goverR) +
      (Age = age) +
      (Gender = female) +
      (Marriage = marriage) +
      (Residence = hukouRural) +
      (Education = edu) +
      (Partymember = party)    ~
        (Mean + SD + Min + Max + (Number = N)),
    title = "Description of Data",
    notes = "Source："
) 


plot_trust <- ggplot(fullDatam,aes(x = year, y = trust_gover_zm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

plot_eco_2019 <- ggplot(fullDatam_2019,aes(x = reorder(province,ecom), y = ecom)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

plot_eco_2021 <- ggplot(fullDatam_2021,aes(x = reorder(province,ecom), y = ecom)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

ggpubr::ggarrange(plot_eco_2017, plot_eco_2019, plot_eco_2021, 
          labels = c("2017", "2019", "2021"),
          ncol = 1, nrow = 3)

plot_gover_2017 <- ggplot(fullDatam_2017,aes(x = reorder(province,goverm), y = goverm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

plot_gover_2019 <- ggplot(fullDatam_2021,aes(x = reorder(province,goverm), y = goverm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

plot_gover_2021 <- ggplot(fullDatam_2021,aes(x = reorder(province,goverm), y = goverm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

ggpubr::ggarrange(plot_gover_2017, plot_gover_2019, plot_gover_2021, 
                  labels = c("2017", "2019", "2021"),
                  ncol = 1, nrow = 3)


plot_public_2017 <- ggplot(fullDatam_2017,aes(x = reorder(province,publicm), y = publicm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5,size = 8))

plot_public_2019 <- ggplot(fullDatam_2019,aes(x = reorder(province,publicm), y = publicm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5,size = 8))

plot_public_2021 <- ggplot(fullDatam_2017,aes(x = reorder(province,publicm), y = publicm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5,size = 8)) 


ggpubr::ggarrange(plot_public_2017, plot_public_2019, plot_public_2021, 
                  labels = c("2017", "2019", "2021"),
                  ncol = 1, nrow = 3)
#plot_trustLocal<- ggplot(fullDatam,aes(x = province, y = trustlm)) +
#  geom_bar(stat="identity") +
#  theme_bw(base_family = "STXihei") +
#  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8)) +
#  facet_grid(year ~.) 


plot_trustLocal_2017 <- ggplot(fullDatam_2017,aes(x = reorder(province,trustlm), y = trustlm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8)) 

plot_trustLocal_2019 <- ggplot(fullDatam_2019,aes(x = reorder(province,trustlm), y = trustlm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

plot_trustLocal_2021 <- ggplot(fullDatam_2021,aes(x = reorder(province,trustlm), y = trustlm)) +
  geom_bar(stat="identity") +
  theme_bw(base_family = "STXihei") +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5,size = 8))

ggpubr::ggarrange(plot_trustLocal_2017, plot_trustLocal_2019, plot_trustLocal_2021, 
          labels = c("2017", "2019", "2021"),
          ncol = 1, nrow = 3)
```

## plotDescrition

# Regression

\`\`\`{r regression} lm_control \<- lm(trust_local \~ eco + gover + public + scales::rescale(age) + party + marriage + female + race + hukouRural + edu + socialLevel + as.factor(province),data = fullData)
